export default {
  PARSE_QUERY_PARAMS: 'PARSE_QUERY_PARAMS',
  QUOTES_LOADING: 'QUOTES_LOADING',
  QUOTES_LOADED: 'QUOTES_LOADED',
  SELECT_ALL: 'SELECT_ALL',
  DESELECT_ALL: 'DESELECT_ALL',
  TOGGLE_SELECT: 'TOGGLE_SELECT',
  QUOTE_DELETED: 'QUOTE_DELETED',
  QUOTES_DELETED: 'QUOTES_DELETED',
  QUOTE_UPDATED: 'QUOTE_UPDATED',
};
