export default {
  SIGN_IN: 'SIGN_IN',
  SIGN_OUT: 'SIGN_OUT',
  AUTHENTICATION_COMPLETE: 'AUTHENTICATION_COMPLETE',
  INCREMENT_LIKE: 'INCREMENT_LIKE',
  DECREMENT_LIKE: 'DECREMENT_LIKE',
  INCREMENT_SUBMITTED: 'INCREMENT_SUBMITTED',
  DECREMENT_SUBMITTED: 'DECREMENT_SUBMITTED',
};
