export default {
  RESET: 'RESET',
  RESET_ALL: 'RESET_ALL',
  SET_VALUE: 'SET_VALUE',
  TOGGLE_SELECT: 'TOGGLE_SELECT',
  VALIDATE: 'VALIDATE',
  PARSE_QUERY_PARAMS: 'PARSE_QUERY_PARAMS',
  QUOTE_STATUSES_LOADED: 'QUOTE_STATUSES_LOADED',
};
